// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAFimYyDJLI25_Mrygk-eNcdxXNEvZEhKM",
    appId: '1:394292667568:web:7668b5983f87b816078775',
    messagingSenderId: '394292667568',
    projectId: 'salescrm-a03fd',
    authDomain: 'salescrm-a03fd.firebaseapp.com',
    storageBucket: 'salescrm-a03fd.appspot.com',
    measurementId: 'G-5SQY2KMWZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1gggrdXjTJnEpu-AK5xwPGdo1HluW_4',
    appId: '1:394292667568:android:455628fb9cae222a078775',
    messagingSenderId: '394292667568',
    projectId: 'salescrm-a03fd',
    storageBucket: 'salescrm-a03fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJjglKH9jMB08AJJ1Qb0lqG3i8NA5yO4',
    appId: '1:394292667568:ios:5523aa9eb7ce8fa4078775',
    messagingSenderId: '394292667568',
    projectId: 'salescrm-a03fd',
    storageBucket: 'salescrm-a03fd.appspot.com',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJjglKH9jMB08AJJ1Qb0lqG3i8NA5yO4',
    appId: '1:394292667568:ios:189716fdc5fac5f6078775',
    messagingSenderId: '394292667568',
    projectId: 'salescrm-a03fd',
    storageBucket: 'salescrm-a03fd.appspot.com',
    iosBundleId: 'com.example.crm.RunnerTests',
  );
}
